disabled_rules: # rule identifiers to exclude from running
  - block_based_kvo
  - colon
  - file_length
  - force_try
  - large_tuple
  - multiple_closures_with_trailing_closure
  - trailing_comma
  - trailing_whitespace
  - type_body_length
  - xctfail_message

opt_in_rules:
  - explicit_init
  - fatal_error_message

function_body_length: # parameterized rules are first parameterized as a warning level, then error level.
  - 60 # warning
  - 70 # error
implicit_getter: error
line_length: 180
mark: error
syntactic_sugar: error
todo: error

